### PR TITLE
Feature: Remove failed processes from history

### PR DESCRIPTION
**Pull request by gokulprathin8**

### CODE REVIEW

**Comment by VisheshSaluja** [comment]
First time using Remove failed history button worked
Then i created a new process and tried the button, but the prompt did not go away after clicking ok
Then i got this console error when the promt finally stopped

Screenshot 2024-08-23 at 11 17 29 PM

**Comment by gokulprathin8** [comment]
> p

added a length > 0 check, check if that fixes the issue?

**Comment by VisheshSaluja** [comment]
This is what happens, the delete works but the prompt keeps on appearing
and i think that in the backend it deletes every process history the first time but because the prompt keeps on appearing it throws the console error

and this doesn't happen the first time i use this button on running Geoweaver.
First time it works as expected.

ezgif com-video-to-gif-converter

**Comment by ZihengSun** [comment]
Should be fixed now

**Pull request merged**
